version: '3'
services:

  mysql:
    image: mysql:latest
    container_name: e-commerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: e-commerce-redis
    command: redis-server --requirepass 181199
    ports:
      - "6379:6379"
    volumes:
       - redis-data:/data

      
volumes:
  mysql-data:
  redis-data:


# docker-compose up -d
# docker-compose down
# docker-compose ps
# docker-compose logs
# docker-compose logs -f
# docker-compose exec mysql bash
# docker-compose exec redis bash
# docker-compose exec zookeeper bash
# docker-compose exec kafka bash


# Copy this file to MAIN project folder and run docker-compose up -d